language: node_js
node_js: stable
cache:
  apt: true
  yarn: true
  npm: true
  directories:
  - node_modules
branches:
  only:
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_faf80fe4a5c4_key -iv $encrypted_faf80fe4a5c4_iv
  -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/travis_rsa
- cp .travis/config ~/.ssh/config
- git config --global user.name 'Hackam'
- git config --global user.email '478604622@qq.com'
install:
- npm install hexo-cli -g
- npm install hexo-math --save
- npm install hexo-generator-searchdb --save
- npm install hexo-symbols-count-time --save
- npm install hexo-generator-feed --save
- npm install hexo-wordcount --save
- npm install mermaid --save
- npm install hexo-tag-mermaid --save
- npm install hexo-tag-plantuml --save
- npm install hexo-fontawesome --save

script:
- hexo -version
- hexo clean && hexo g
after_script:
- set -ev
- export TZ='Asia/Hong_Kong'
- cd ./public
- git config user.name "Hackam"
- git config user.email "478604622@qq.com"
- git init
- git add .
- git commit -m "Site updated:`date +"%Y-%m-%d %H:%M:%S"`"
- git remote add origin git@github.com:xeojeo/xeojeo.github.io.git
- git push -u origin master -f
dd:
- openssl aes-256-cbc -K $encrypted_faf80fe4a5c4_key -iv $encrypted_faf80fe4a5c4_iv
  -in travis_rsa.enc -out travis_rsa -d
- openssl aes-256-cbc -K $encrypted_6148c8409cc2_key -iv $encrypted_6148c8409cc2_iv
  -in travis_rsa.enc -out travis_rsa -d
